### ISSUE TITLE
[FEAT] Update tests to run without org secrets

### ISSUE THREAD

**Issue by NeonDaniel** [NeonGeckoCom/neon_mq_connector#97]
### Objective

Refactor unit tests to use public configuration instead of a configuration secret so test config may be saved in the repository.

### Initial Implementation Requirements

- Use Mock objects wherever possible to reduce backend server dependence
- Update tests to only use a test namespace
- Update `neon-api-utils` user to allow access to the test namespace

### Other Considerations

Forked PR fails tests https://github.com/NeonGeckoCom/neon_mq_connector/pull/96

**Comment by NeonKirill** [comment]
Removed dependencies on secrets in https://github.com/NeonGeckoCom/neon_mq_connector/pull/99
